# Generated by Django 5.0.6 on 2024-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Proyecto', models.CharField(max_length=50)),
                ('Estudiante', models.CharField(max_length=50)),
                ('Tema', models.CharField(max_length=50)),
                ('Profesor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Proyectos',
            },
        ),
    ]
