# Generated by Django 5.0.6 on 2024-06-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_proyecto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Tema',
            field=models.CharField(choices=[('Software', 'Software'), ('Matemática', 'Matemática'), ('Física', 'Física')], max_length=50),
        ),
    ]
