# Generated by Django 5.0.6 on 2024-06-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_proyecto_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Patrocinio',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
    ]
